<script setup>
import { publicImgSrc } from "../../utils/public-img-src.js";
import InfoModal from "../InfoModal/index.vue";

const props = defineProps({
  viewMode: {
    type: String,
    required: true,
  },
  showNAdjustControls: {
    type: Boolean,
    default: false,
  },
  canDecrementGroupN: {
    type: Boolean,
    default: false,
  },
  canIncrementGroupN: {
    type: Boolean,
    default: false,
  },
  groupCount: {
    type: Number,
    default: 0,
  },
});

const emit = defineEmits(["change-view-mode", "decrement-n", "increment-n"]);

const modes = [
  { key: "exhibitions", label: "Exhibition", icon: "exhibition" },
  { key: "artist", label: "Artist", icon: publicImgSrc("artist.svg") },
  { key: "institution", label: "Institution", icon: publicImgSrc("institution.svg") },
];

const clusterInfoPoints = [
  "Text is analyzed and compared across 3 distinct sources: exhibitions (exhibition titles and summaries), artists (artist's statements and interviews), and institutions (museum archives' permanent digital collections of artworks and biographical information).",
  "Groups are generated by similarity of patterns within these texts from the selected source and anchored by a keyword that represents its shared theme.",
  "",
  "Each point represents an aggregated average of an artist's analyzed text excerpts from the selected source.",
  "Rectangles and labels that appear on hover indicate the center of a group and its theme keyword.",
  "Points are placed around a group's center based on their similarity to that shared theme and lines are drawn to map this connection - distance/line length and weight indicates the strength of similarity.",
];

function isActive(modeKey) {
  return props.viewMode === modeKey;
}

function iconMaskStyle(iconUrl) {
  return {
    maskImage: `url("${iconUrl}")`,
    WebkitMaskImage: `url("${iconUrl}")`,
  };
}
</script>

<template>
  <div class="cluster-heading">
    <div class="cluster-heading__left">
      <div class="cluster-heading__group-info-wrap">
        <span class="cluster-heading__group-line">Group artists by words of</span>
        <div class="cluster-heading__group-info-button">
            <InfoModal
              heading="Methodology"
              :bullet-points="clusterInfoPoints"
              aria-label="Open methodology information"
              small-text
            />
          </div>
        </div>
      <div class="cluster-heading__toggle-row">
        <div class="cluster-heading__toggle" role="tablist" aria-label="Cluster grouping mode">
          <button
            v-for="mode in modes"
            :key="mode.key"
            type="button"
            class="cluster-heading__toggle-btn label-text"
            :class="{ 'cluster-heading__toggle-btn--active': isActive(mode.key) }"
            @click="emit('change-view-mode', mode.key)"
          >
            <span
              v-if="mode.icon === 'exhibition'"
              class="cluster-heading__exhibition-node"
              aria-hidden="true"
            />
            <span
              v-else
              class="cluster-heading__mode-icon"
              :style="iconMaskStyle(mode.icon)"
              aria-hidden="true"
            />
            <span class="cluster-heading__toggle-label">{{ mode.label }}</span>
          </button>
        </div>
        <div class="cluster-heading__group-count-controls">
          <button
            v-if="showNAdjustControls && canDecrementGroupN"
            type="button"
            class="cluster-heading__group-count-step-btn label-text"
            aria-label="Decrease groups"
            @click="emit('decrement-n')"
          >
            -
          </button>
          <div class="cluster-heading__group-count-value label-text" aria-live="polite">
            {{ groupCount }} groups
          </div>
          <button
            v-if="showNAdjustControls && canIncrementGroupN"
            type="button"
            class="cluster-heading__group-count-step-btn label-text"
            aria-label="Increase groups"
            @click="emit('increment-n')"
          >
            +
          </button>
        </div>
      </div>
      <div class="cluster-heading__subtitle">
        <div class="cluster-heading__subtitle-info-wrap">
          <p>Similarity groups center around themes extracted from these source texts.</p>
        </div>
        <p>Select points and groups to view more details.</p>
      </div>
    </div>
  </div>
</template>

<style scoped src="./style.css"></style>
